### ISSUE TITLE
Deploy NaN bug fix to npm

### ISSUE THREAD

**Issue by rreusser** [rreusser/react-native-paged-scroll-view#7]
Needs deploy. Away from computer at the moment. Will deploy ASAP. Until then will have to use git master directly. Sorry for any inconvenience!

**Comment by rreusser** [comment]
@Yu-Liang — deployed to npm. Version is a little crazy because was getting frustrated sanity-checking our internal build, but your fix should be on npm now.

**Comment by reddingit** [comment]
Thanks
