### ISSUE TITLE
Changing content dynamically

### ISSUE THREAD

**Issue by sercanov** [rreusser/react-native-paged-scroll-view#9]
I try to change childs dynamically when page changed but i couldn't do it. Is it not supported or I just couldn't manage to do it ? 

Thanks

**Comment by rreusser** [comment]
Hmm. So what's the setup? When the page changes you use setState to pass the page to the children? Does componentWillReceiveProps fire? Can you add console logs and see which parts are happening? I think I did something that sounds similar (changing colors when the slide changed) and managed to get it working, but maybe this is a different case.

**Comment by sercanov** [comment]
When I log "this.props.children" on the render, it logs the changed pages but doesn't render the new pages. I ll try to use componentWillRecieveProps or maybe it's related with onContentSizeChange..
